spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.79.129:3306/gulimall_ums?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.79.129:8848
  application:
    name:gulimail-member

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto


server:
  port: 8000